# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue Frontend
    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      name: Install packages
    - run: npm install
    - name: Install packages
      run: cd frontend
    - name: Vue Build
      run: vue-cli-service build --dest build
